### PR TITLE
[6] Moved review/approve button to Audit Pannel

### PR DESCRIPTION
**Pull request by alexandre-lavoie**
_Note: The merge leads to a somewhat awkward button placement. Let me know what a good solution could be!_

The review button used to be only accessible through general information.

The button was moved at the bottom of the sections.

audit-review

### CODE REVIEW

**Comment by lm-sec** [comment]
maybe move it on the left of the download button, iirc it is the same component as where you just put it

**Comment by alexandre-lavoie** [comment]
Good idea! I may change it to an icon then (I'll try to find something that makes sense + I'll add a tooltip)

**Comment by alexandre-lavoie** [comment]
This is now a button in top bar. The following are each button state. If you have any issues, let me know!

_Creator/collaborator_

When audit is in edit mode:

audit-edit

When audit is in review mode:

audit-review-button

_Reviewer_

When reviewer did not approve yet (or removed his approval):

audit-not-approved

When reviewer approved:

audit-approval

**Comment by alexandre-lavoie** [comment]
Remade in a recent commit. Closing in favor of already merged version.

**Pull request closed without merging**
